version: "0.5"

# Process-Compose orchestrates local development processes
# Start: task dev:up (or process-compose up)
# Stop: task dev:down (or Ctrl+C)
# Docs: https://f1bonacc1.github.io/process-compose/

processes:
  hugo:
    command: hugo server --buildDrafts --buildFuture --bind 0.0.0.0
    working_dir: .
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 1313
        path: "/"
      initial_delay_seconds: 3
      period_seconds: 5
      failure_threshold: 3
    availability:
      restart: on_failure
      max_restarts: 3

  # Optional: Enable when actively translating
  translate-watch:
    command: task translate:watch
    depends_on:
      hugo:
        condition: process_healthy
    disabled: true

  # Optional: Enable for subscriber sync
  mailerlite-sync:
    command: task mailerlite:stats
    depends_on:
      hugo:
        condition: process_healthy
    disabled: true

  # Optional: Enable for webhook server (receives Web3Forms submissions)
  mailerlite-webhook:
    command: task mailerlite:server GROUP_ID=173641063022462964
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 8086
        path: "/health"
      initial_delay_seconds: 2
      period_seconds: 10
    availability:
      restart: on_failure
      max_restarts: 3
    disabled: true
