version: '3'

dotenv: ['.env']

vars:
  # Project
  PROJECT_NAME: ubuntusoftware-net
  DOMAIN: www.ubuntusoftware.net

  # Commands & Binaries
  TRANSLATE_CMD: cmd/translate/main.go
  BIN_DIR: bin

  # Directories (for .gitignore generation)
  DIR_PUBLIC: public
  DIR_RESOURCES: resources
  DIR_NODE_MODULES: node_modules
  DIR_BIN: bin

  # Files (for .gitignore)
  FILE_HUGO_LOCK: .hugo_build.lock
  FILE_ENV: .env
  FILE_GO_SUM: go.sum

  # Hugo flags
  HUGO_BUILD_FLAGS: --gc --minify
  HUGO_DEV_FLAGS: --buildDrafts --buildFuture

  # Go settings
  GO_VERSION: "1.24"
  CGO_ENABLED: "1"

tasks:
  setup:
    desc: Complete setup - install Hugo, Bun, and dependencies
    cmds:
      - task: install:hugo
      - task: install:bun
      - task: install:deps

  install:hugo:
    desc: Install Hugo Extended via Go
    cmds:
      - echo "Installing Hugo Extended..."
      - CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@latest
      - hugo version
    env:
      CGO_ENABLED: "1"

  install:bun:
    desc: Install Bun
    cmds:
      - |
        if command -v bun &> /dev/null; then
          echo "Bun already installed"
        else
          curl -fsSL https://bun.sh/install | bash
        fi
      - bun --version

  install:deps:
    desc: Install dependencies
    cmds:
      - bun install
      - go mod download

  dev:
    desc: Start Hugo development server
    cmds:
      - hugo server {{.HUGO_DEV_FLAGS}}

  build:
    desc: Build production site
    cmds:
      - hugo {{.HUGO_BUILD_FLAGS}}

  preview:
    desc: Preview production build
    cmds:
      - hugo server -e production --minify

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.DIR_PUBLIC}} {{.DIR_RESOURCES}} {{.FILE_HUGO_LOCK}}

  translate:check:
    desc: Check which files need translation
    cmds:
      - go run {{.TRANSLATE_CMD}} --check

  translate:all:
    desc: Translate all changed content
    cmds:
      - go run {{.TRANSLATE_CMD}} --all

  translate:lang:
    desc: Translate to specific language
    cmds:
      - go run {{.TRANSLATE_CMD}} --lang={{.LANG}}
    requires:
      vars: [LANG]

  translate:i18n:
    desc: Translate i18n files
    cmds:
      - go run {{.TRANSLATE_CMD}} --i18n

  cf:login:
    desc: Login to Cloudflare
    cmds:
      - bunx wrangler login

  cf:init:
    desc: Initialize Cloudflare Pages project
    cmds:
      - bunx wrangler pages project create {{.PROJECT_NAME}} --production-branch=main

  cf:deploy:
    desc: Deploy to Cloudflare Pages
    deps: [build]
    cmds:
      - bunx wrangler pages deploy public --project-name={{.PROJECT_NAME}}

  cf:status:
    desc: Check deployment status
    cmds:
      - bunx wrangler pages deployment list --project-name={{.PROJECT_NAME}}

  ci:setup:
    desc: Setup CI environment
    cmds:
      - CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@latest
      - bun install
      - go mod download
    env:
      CGO_ENABLED: "1"

  ci:build:
    desc: Build in CI
    deps: [build]

  ci:deploy:
    desc: Deploy from CI
    cmds:
      - bunx wrangler pages deploy public --project-name={{.PROJECT_NAME}}

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  lint:
    desc: Lint code
    cmds:
      - go vet ./...

  test:
    desc: Run tests
    cmds:
      - go test ./... -v

  help:
    desc: Show help
    cmds:
      - task --list
