version: '3'

dotenv: ['.env']

vars:
  # Project
  PROJECT_NAME: ubuntusoftware-net
  DOMAIN: www.ubuntusoftware.net

  # Paths
  TRANSLATE_CMD: cmd/translate/main.go
  DIR_PUBLIC: public
  DIR_RESOURCES: resources
  DIR_NODE_MODULES: node_modules
  DIR_BIN: bin
  DIR_PLAYWRIGHT: .playwright-mcp

  # Files
  FILE_HUGO_LOCK: .hugo_build.lock
  FILE_HUGO_STATS: hugo_stats.json
  FILE_BUN_LOCK: bun.lockb
  FILE_NPM_LOCK: package-lock.json
  FILE_ENV: .env

  # Hugo
  HUGO_BUILD_FLAGS: --gc --minify
  HUGO_DEV_FLAGS: --buildDrafts --buildFuture

  # Go
  GO_VERSION: "1.24"
  CGO_ENABLED: "1"

tasks:
  # Environment Management
  env:setup:
    desc: "Setup environment - interactive wizard for API keys"
    cmds:
      - go run cmd/env/main.go wizard

  env:show:
    desc: "Show current environment configuration"
    cmds:
      - go run cmd/env/main.go show

  env:sync:
    desc: "Sync .env to GitHub repository secrets for CI/CD"
    cmds:
      - go run cmd/env/main.go sync-secrets {{.CLI_ARGS}}
      - |
        REPO=$(gh repo view --json owner,name --jq '"\(.owner.login)/\(.name)"' 2>/dev/null || echo "")
        if [ -n "$REPO" ]; then
          echo ""
          echo "→ View secrets: https://github.com/$REPO/settings/secrets/actions"
          echo ""
        fi

  setup:
    desc: Complete setup - install Hugo, Bun, and dependencies
    cmds:
      - task: install:hugo
      - task: install:bun
      - task: install:deps

  install:hugo:
    desc: Install Hugo Extended via Go
    cmds:
      - echo "Installing Hugo Extended..."
      - CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@latest
      - hugo version
    env:
      CGO_ENABLED: "1"

  install:bun:
    desc: Install Bun
    cmds:
      - |
        if command -v bun &> /dev/null; then
          echo "Bun already installed"
        else
          curl -fsSL https://bun.sh/install | bash
        fi
      - bun --version

  install:deps:
    desc: Install dependencies
    cmds:
      - bun install
      - go mod download

  dev:
    desc: Start Hugo development server
    cmds:
      - hugo server {{.HUGO_DEV_FLAGS}}

  build:
    desc: Build production site
    cmds:
      - hugo {{.HUGO_BUILD_FLAGS}}

  preview:
    desc: Preview production build
    cmds:
      - hugo server -e production --minify

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.DIR_PUBLIC}} {{.DIR_RESOURCES}} {{.FILE_HUGO_LOCK}}

  translate:check:
    desc: Check which files need translation
    cmds:
      - go run {{.TRANSLATE_CMD}} --check

  translate:all:
    desc: Translate all changed content
    cmds:
      - go run {{.TRANSLATE_CMD}} --all

  translate:lang:
    desc: Translate to specific language
    cmds:
      - go run {{.TRANSLATE_CMD}} --lang={{.LANG}}
    requires:
      vars: [LANG]

  translate:i18n:
    desc: Translate i18n files
    cmds:
      - go run {{.TRANSLATE_CMD}} --i18n

  cf:login:
    desc: Login to Cloudflare
    cmds:
      - bunx wrangler login

  cf:init:
    desc: Initialize Cloudflare Pages project
    cmds:
      - bunx wrangler pages project create {{.PROJECT_NAME}} --production-branch=main

  cf:deploy:
    desc: Deploy to Cloudflare Pages
    deps: [build]
    cmds:
      - bunx wrangler pages deploy {{.DIR_PUBLIC}} --project-name={{.PROJECT_NAME}}

  cf:status:
    desc: Check deployment status
    cmds:
      - bunx wrangler pages deployment list --project-name={{.PROJECT_NAME}}

  cf:delete:
    desc: Delete Cloudflare Pages project
    cmds:
      - bunx wrangler pages project delete {{.PROJECT_NAME}}

  ci:setup:
    desc: Setup CI environment
    cmds:
      - CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@latest
      - bun install
      - go mod download
    env:
      CGO_ENABLED: "1"

  ci:build:
    desc: Build in CI
    deps: [build]

  ci:deploy:
    desc: Deploy from CI
    cmds:
      - bunx wrangler pages deploy {{.DIR_PUBLIC}} --project-name={{.PROJECT_NAME}}

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  lint:
    desc: Lint code
    cmds:
      - go vet ./...

  test:
    desc: Run tests
    cmds:
      - go test ./... -v

  generate:gitignore:
    desc: Generate .gitignore from vars
    cmds:
      - |
        cat > .gitignore << 'EOF'
        # Hugo
        {{.DIR_PUBLIC}}/
        {{.DIR_RESOURCES}}/
        {{.FILE_HUGO_LOCK}}
        {{.FILE_HUGO_STATS}}

        # Node/Bun
        {{.DIR_NODE_MODULES}}/
        {{.FILE_BUN_LOCK}}
        {{.FILE_NPM_LOCK}}

        # Go
        {{.DIR_BIN}}/
        go.sum
        *.test
        *.out

        # Environment
        {{.FILE_ENV}}
        {{.FILE_ENV}}.*

        # Testing
        {{.DIR_PLAYWRIGHT}}/

        # IDE & OS
        .vscode/
        .DS_Store
        EOF

  git:commit:
    desc: Generate gitignore, commit and push changes
    cmds:
      - task: generate:gitignore
      - git add -A
      - git commit -m "{{.MESSAGE}}" || true
      - git push
      - |
        REPO=$(gh repo view --json owner,name --jq '"\(.owner.login)/\(.name)"' 2>/dev/null || echo "")
        if [ -n "$REPO" ]; then
          echo ""
          echo "✓ Pushed to: https://github.com/$REPO"
          echo ""
        fi

  help:
    desc: Show help
    cmds:
      - task --list
