version: '3'

# =============================================================================
# Ubuntu Website - Root Taskfile
# =============================================================================
#
# This is the root Taskfile that includes all domain-specific modules.
# Most tasks are defined in taskfiles/*.yml for organization.
#
# Quick Reference:
#   task                 - Show project info
#   task dev             - Start Hugo dev server
#   task build           - Build production site
#   task git:deploy      - Commit and deploy
#   task help            - List all tasks
#
# Module Namespaces:
#   hugo:*      - Hugo static site generator
#   cf:*        - Cloudflare Pages management
#   git:*       - Git operations
#   translate:* - Translation workflow
#   cfanalytics:* - Cloudflare Web Analytics (cmd/cfanalytics)
#   sitecheck:* - Site reachability checks (cmd/sitecheck)
#   genlogo:*   - Logo/branding generation (cmd/genlogo)
#   mailerlite:* - MailerLite subscriber management (cmd/mailerlite)
#   vanityimport:* - Go vanity import packages (cmd/vanityimport)
#   google:*    - All Google services unified (cmd/google)
#   airspace:*  - Airspace demo and FAA data tools (cmd/airspace)
#   r2:*        - R2 object storage for large static assets
#   env:*       - Environment management
#   url:*       - URL shortcuts + SEO dashboards
#   tools:*     - Tools (gh, task, etc.)
#   release:*   - Release builds for binary tools
#   ci:*        - CI interface tasks
#   dev:*       - Development workflow (wraps pc + tui)
#   pc:*        - Process-Compose (dev process orchestration)
#   tui:*       - Task-UI (web dashboard for tasks)
#
# =============================================================================

# =============================================================================
# Includes
# =============================================================================

includes:
  # Domain modules
  hugo: ./taskfiles/Taskfile.hugo.yml
  cf: ./taskfiles/Taskfile.cf.yml
  translate: ./taskfiles/Taskfile.translate.yml
  autotranslate: ./taskfiles/Taskfile.autotranslate.yml
  cfanalytics: ./taskfiles/Taskfile.cfanalytics.yml
  sitecheck: ./taskfiles/Taskfile.sitecheck.yml
  genlogo: ./taskfiles/Taskfile.genlogo.yml
  mailerlite: ./taskfiles/Taskfile.mailerlite.yml
  google: ./taskfiles/Taskfile.google.yml
  youtube: ./taskfiles/Taskfile.youtube.yml
  env: ./taskfiles/Taskfile.env.yml
  url: ./taskfiles/Taskfile.url.yml

  # Infrastructure modules
  lanip: ./taskfiles/Taskfile.lanip.yml

  # Tools (git exposed at top-level for convenience: git:deploy, git:status)
  git:
    taskfile: ./taskfiles/tools/Taskfile.git.yml
  tools: ./taskfiles/Taskfile.tools.yml

  # Release builds
  release: ./taskfiles/Taskfile.release.yml

  # Development workflow
  dev: ./taskfiles/Taskfile.dev.yml
  pc: ./taskfiles/tools/Taskfile.process-compose.yml
  tui: ./taskfiles/tools/Taskfile.task-ui.yml
  wrangler: ./taskfiles/tools/Taskfile.wrangler.yml

  # MCP servers
  google-mcp: ./taskfiles/tools/Taskfile.google-mcp.yml

  # Claude CLI (for autotranslate claude-cli provider)
  claude-cli: ./taskfiles/tools/Taskfile.claude-cli.yml

  # Browser automation
  playwright: ./taskfiles/tools/Taskfile.playwright.yml

  # Cloudflare Workers (serverless webhooks)
  workers: ./taskfiles/Taskfile.workers.yml

  # Go vanity imports (/pkg/)
  vanityimport: ./taskfiles/Taskfile.vanityimport.yml

  # Airspace demo (BVLOS development)
  airspace: ./taskfiles/Taskfile.airspace.yml

  # R2 object storage (large static assets)
  r2: ./taskfiles/Taskfile.cf-r2.yml

  # Toki i18n toolkit (fork: joeblew999/toki)
  toki: ./taskfiles/Taskfile.toki.yml

# =============================================================================
# Environment
# =============================================================================

dotenv:
  - '.env'

# =============================================================================
# Variables
# =============================================================================

vars:
  # Project
  PROJECT_NAME: ubuntu-website
  DOMAIN: www.ubuntusoftware.net

  # Cloudflare Account
  CF_ACCOUNT_ID: 7384af54e33b8a54ff240371ea368440
  CF_ZONE_ID: 867fb5996096b895b47114b6564ee0fb
  CF_WEB_ANALYTICS_SITE_TAG: 4c28a6bfb5514996914a603c999d5c79

  # Deployment URLs
  URL_PRODUCTION: https://www.ubuntusoftware.net
  URL_PREVIEW: https://ubuntu-website.pages.dev
  URL_DEV: http://localhost:1313

  # Commands
  ENV_CMD: cmd/env/main.go

  # Directories (gitignored)
  DIR_PUBLIC: public
  DIR_RESOURCES: resources
  DIR_NODE_MODULES: node_modules
  DIR_BUILD: .build
  DIR_PLAYWRIGHT: .playwright-mcp
  DIR_VIA: .via
  DIR_LOGS: logs
  DIR_TASK: .task

  # Files (gitignored)
  FILE_HUGO_LOCK: .hugo_build.lock
  FILE_HUGO_STATS: hugo_stats.json
  FILE_BUN_LOCK: bun.lockb
  FILE_NPM_LOCK: package-lock.json
  FILE_ENV: .env
  FILE_ANALYTICS_STATE: .analytics-state.json
  FILE_SITECHECK_STATE: .sitecheck-state.json

  # Hugo
  HUGO_BUILD_FLAGS: --gc --minify
  HUGO_DEV_FLAGS: --buildDrafts --buildFuture
  HUGO_PREVIEW_FLAGS: -e production --minify

  # Go
  GO_VERSION: "1.25"
  CGO_ENABLED: "1"

  # Wrangler (installed via wrangler:check:deps)
  # Full path since ~/.bun/bin may not be in PATH
  WRANGLER_CMD: '{{.HOME}}/.bun/bin/wrangler'

  # Global binary install directory - all tools use this
  # Unix: ~/.local/bin (standard for user binaries)
  # Windows: ~/bin (simpler path)
  BIN_INSTALL_DIR: '{{if eq OS "windows"}}{{.HOME}}/bin{{else}}{{.HOME}}/.local/bin{{end}}'

  # Global source directory - for cloned forks and upstream repos
  # Used by google-mcp, playwright, etc.
  SRC_DIR: '{{.ROOT_DIR}}/.src'

  

# =============================================================================
# Tasks
# =============================================================================

tasks:
  # ===========================================================================
  # Default & Info
  # ===========================================================================

  default:
    desc: Show project information (runs when you type 'task')
    cmds:
      - task: info

  info:
    desc: Show all URLs and project information
    cmds:
      - |
        # Get branch info
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

        echo "========================================"
        echo "Ubuntu Website - Project Info"
        echo "========================================"
        echo ""

        # Branch Status - PROMINENT DISPLAY
        echo "========== GIT BRANCH =========="
        if [ "$CURRENT_BRANCH" = "main" ]; then
          echo "WARNING: You are on MAIN branch"
          echo "Commits will deploy to PRODUCTION!"
        else
          echo "Current branch: $CURRENT_BRANCH"
          echo "(Safe to commit - preview deployment)"
        fi
        echo "================================"
        echo ""

        echo "Project: {{.PROJECT_NAME}}"
        echo "Domain: {{.DOMAIN}}"
        echo ""
        echo "Development URL:"
        echo "  Local: {{.URL_DEV}}"
        echo ""
        echo "Production URLs:"
        echo "  Main: {{.URL_PRODUCTION}}"
        echo "  Preview: {{.URL_PREVIEW}}"
        echo ""
        COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
        if [ "$COMMIT" != "unknown" ]; then
          echo "Current Commit Preview:"
          echo "  https://$COMMIT.ubuntu-website.pages.dev"
          echo ""
        fi
        echo "Cloudflare Dashboards:"
        echo "  Domain: https://dash.cloudflare.com/{{.CF_ACCOUNT_ID}}/ubuntusoftware.net"
        echo "  Pages: https://dash.cloudflare.com/{{.CF_ACCOUNT_ID}}/pages/view/{{.PROJECT_NAME}}"
        echo "  Settings: https://dash.cloudflare.com/{{.CF_ACCOUNT_ID}}/pages/view/{{.PROJECT_NAME}}/settings/production"
        echo ""
        echo "Quick Commands:"
        echo "  task setup             - Install Hugo, Bun, dependencies"
        echo "  task dev               - Start development server"
        echo "  task url:dev           - Open local dev in browser"
        echo "  task build             - Build production site"
        echo "  task git:deploy        - Commit and deploy to production"
        echo "  task cf:status         - Check deployment status"
        echo "  task url:prod          - Open production site"
        echo "  task help              - Show all available tasks"
        echo "========================================"

  help:
    desc: Show help
    cmds:
      - task --list

  # ===========================================================================
  # Setup & Installation
  # ===========================================================================

  setup:
    desc: Complete setup - install Hugo, Bun, and dependencies
    cmds:
      - task: install:hugo
      - task: install:bun
      - task: install:deps

  install:hugo:
    desc: Install Hugo Extended (via Homebrew)
    cmds:
      - |
        if command -v hugo &> /dev/null; then
          echo "Hugo already installed"
          hugo version
        else
          echo "Installing Hugo Extended via Homebrew..."
          brew install hugo
          hugo version
        fi

  install:bun:
    desc: Install Bun
    cmds:
      - |
        if command -v bun &> /dev/null; then
          echo "Bun already installed"
        else
          curl -fsSL https://bun.sh/install | bash
        fi
      - bun --version

  install:deps:
    desc: Install dependencies
    cmds:
      - bun install
      - go mod download

  # ===========================================================================
  # Aliases (backward compatibility)
  # ===========================================================================

  dev:
    desc: "[alias] Start Hugo development server"
    cmds:
      - task: hugo:dev

  dev:lan:
    desc: "[alias] Start Hugo dev server with LAN IP"
    cmds:
      - task: hugo:dev:lan

  build:
    desc: "[alias] Build production site"
    cmds:
      - task: hugo:build

  preview:
    desc: "[alias] Preview production build"
    cmds:
      - task: hugo:preview

  clean:
    desc: "[alias] Clean build artifacts"
    cmds:
      - task: hugo:clean

  # ===========================================================================
  # CI Interface (called by GitHub Actions workflows)
  # ===========================================================================
  # Workflows call these tasks - all logic stays in Taskfile.
  # Note: ci:cfanalytics and ci:sitecheck use binaries via their respective taskfiles

  ci:health:
    desc: "[Monitor] Health - Run health checks for CI"
    cmds:
      - task: git:check:health

  ci:health:test-fail:
    desc: "[Monitor] Health - Force failure to test notifications"
    cmds:
      - echo "Simulating health check failure..."
      - exit 1

  ci:cfanalytics:
    desc: "[Monitor] Cloudflare Analytics - Run analytics check for CI"
    deps: [cfanalytics:check:deps]
    cmds:
      - '{{.HOME}}/.local/bin/cfanalytics{{exeExt}} -github-issue'

  ci:sitecheck:
    desc: "[Monitor] Sitecheck - Run site check for CI"
    deps: [sitecheck:check:deps]
    cmds:
      - '{{.HOME}}/.local/bin/sitecheck{{exeExt}} -github-issue'

  ci:translate:
    desc: "[Monitor] Translate - Check translation status for CI"
    deps: [translate:check:deps]
    vars:
      TRANSLATE: '{{.HOME}}/.local/bin/translate{{exeExt}}'
    cmds:
      # Run all checks, output markdown report
      # Exits non-zero if ANY check finds issues
      - |
        echo "# Translation Status Report"
        echo ""
        FOUND=0
        {{.TRANSLATE}} -github-issue content missing || FOUND=1
        {{.TRANSLATE}} -github-issue content stale || FOUND=1
        {{.TRANSLATE}} -github-issue content orphans || FOUND=1
        {{.TRANSLATE}} -github-issue menu check || FOUND=1
        [ $FOUND -eq 0 ]

  # ===========================================================================
  # Code Quality
  # ===========================================================================

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  lint:
    desc: Lint code
    cmds:
      - go vet ./...

  test:
    desc: Run tests
    cmds:
      - go test ./... -v
