version: '3'

dotenv: ['.env']

vars:
  # Project
  PROJECT_NAME: ubuntusoftware-net
  DOMAIN: www.ubuntusoftware.net

  # Commands
  ENV_CMD: cmd/env/main.go
  TRANSLATE_CMD: cmd/translate/main.go

  # Directories
  DIR_PUBLIC: public
  DIR_RESOURCES: resources
  DIR_NODE_MODULES: node_modules
  DIR_BIN: bin
  DIR_PLAYWRIGHT: .playwright-mcp
  DIR_VIA: .via

  # Files
  FILE_HUGO_LOCK: .hugo_build.lock
  FILE_HUGO_STATS: hugo_stats.json
  FILE_BUN_LOCK: bun.lockb
  FILE_NPM_LOCK: package-lock.json
  FILE_ENV: .env

  # Hugo
  HUGO_BUILD_FLAGS: --gc --minify
  HUGO_DEV_FLAGS: --buildDrafts --buildFuture
  HUGO_PREVIEW_FLAGS: -e production --minify

  # Go
  GO_VERSION: "1.24"
  CGO_ENABLED: "1"

  # Wrangler
  WRANGLER_CMD: bunx wrangler

tasks:
  # ============================================================================
  # Setup & Installation
  # ============================================================================

  setup:
    desc: Complete setup - install Hugo, Bun, and dependencies
    cmds:
      - task: install:hugo
      - task: install:bun
      - task: install:deps

  install:hugo:
    desc: Install Hugo Extended via Go
    cmds:
      - echo "Installing Hugo Extended..."
      - go install -tags extended github.com/gohugoio/hugo@latest
      - hugo version
    env:
      CGO_ENABLED: '{{.CGO_ENABLED}}'

  install:bun:
    desc: Install Bun
    cmds:
      - |
        if command -v bun &> /dev/null; then
          echo "Bun already installed"
        else
          curl -fsSL https://bun.sh/install | bash
        fi
      - bun --version

  install:deps:
    desc: Install dependencies
    cmds:
      - bun install
      - go mod download

  # ============================================================================
  # Environment Management
  # ============================================================================

  env:local:setup:
    desc: "Validate local .env credentials"
    cmds:
      - go run {{.ENV_CMD}} local-setup

  env:local:list:
    desc: "List local .env configuration"
    cmds:
      - go run {{.ENV_CMD}} local-list

  env:web:gui:
    desc: "Open web GUI for environment setup"
    cmds:
      - go run {{.ENV_CMD}} web-gui

  env:web:gui-mock:
    desc: "Open web GUI with mock validation (for testing)"
    cmds:
      - go run {{.ENV_CMD}} web-gui-mock

  env:gh:list:
    desc: "List GitHub secrets"
    cmds:
      - go run {{.ENV_CMD}} gh-list

  env:gh:push:
    desc: "Push .env to GitHub secrets"
    cmds:
      - go run {{.ENV_CMD}} gh-push {{.CLI_ARGS}}

  env:all:
    desc: "Complete environment workflow (setup → push to GitHub)"
    cmds:
      - task: env:local:setup
      - task: env:gh:push
      - task: env:gh:list

  # ============================================================================
  # Development
  # ============================================================================

  dev:
    desc: Start Hugo development server
    cmds:
      - hugo server {{.HUGO_DEV_FLAGS}}

  build:
    desc: Build production site
    cmds:
      - hugo {{.HUGO_BUILD_FLAGS}}

  preview:
    desc: Preview production build
    cmds:
      - hugo server {{.HUGO_PREVIEW_FLAGS}}

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.DIR_PUBLIC}} {{.DIR_RESOURCES}} {{.FILE_HUGO_LOCK}}

  # ============================================================================
  # Translation
  # ============================================================================

  translate:check:
    desc: Check which files need translation
    cmds:
      - go run {{.TRANSLATE_CMD}} --check

  translate:all:
    desc: Translate all changed content
    cmds:
      - go run {{.TRANSLATE_CMD}} --all

  translate:lang:
    desc: Translate to specific language
    cmds:
      - go run {{.TRANSLATE_CMD}} --lang={{.LANG}}
    requires:
      vars: [LANG]

  translate:i18n:
    desc: Translate i18n files
    cmds:
      - go run {{.TRANSLATE_CMD}} --i18n

  # ============================================================================
  # Cloudflare Pages
  # ============================================================================

  cf:login:
    desc: Login to Cloudflare
    cmds:
      - '{{.WRANGLER_CMD}} login'

  cf:init:
    desc: Initialize Cloudflare Pages project
    cmds:
      - '{{.WRANGLER_CMD}} pages project create {{.PROJECT_NAME}} --production-branch=main'

  cf:deploy:
    desc: Deploy to Cloudflare Pages
    deps: [build]
    cmds:
      - '{{.WRANGLER_CMD}} pages deploy {{.DIR_PUBLIC}} --project-name={{.PROJECT_NAME}}'

  cf:status:
    desc: Check deployment status
    cmds:
      - '{{.WRANGLER_CMD}} pages deployment list --project-name={{.PROJECT_NAME}}'

  cf:delete:
    desc: Delete Cloudflare Pages project
    cmds:
      - '{{.WRANGLER_CMD}} pages project delete {{.PROJECT_NAME}}'

  # ============================================================================
  # CI/CD
  # ============================================================================

  ci:setup:
    desc: Setup CI environment
    cmds:
      - go install -tags extended github.com/gohugoio/hugo@latest
      - bun install
      - go mod download
    env:
      CGO_ENABLED: '{{.CGO_ENABLED}}'

  ci:build:
    desc: Build in CI
    deps: [build]

  ci:deploy:
    desc: Deploy from CI
    cmds:
      - '{{.WRANGLER_CMD}} pages deploy {{.DIR_PUBLIC}} --project-name={{.PROJECT_NAME}}'

  # ============================================================================
  # Code Quality
  # ============================================================================

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  lint:
    desc: Lint code
    cmds:
      - go vet ./...

  test:
    desc: Run tests
    cmds:
      - go test ./... -v

  # ============================================================================
  # Git Utilities
  # ============================================================================

  generate:gitignore:
    desc: Generate .gitignore from vars
    cmds:
      - |
        cat > .gitignore << 'EOF'
        # Hugo
        {{.DIR_PUBLIC}}/
        {{.DIR_RESOURCES}}/
        {{.FILE_HUGO_LOCK}}
        {{.FILE_HUGO_STATS}}

        # Node/Bun
        {{.DIR_NODE_MODULES}}/
        {{.FILE_BUN_LOCK}}
        {{.FILE_NPM_LOCK}}

        # Go
        {{.DIR_BIN}}/
        go.sum
        *.test
        *.out

        # Environment
        {{.FILE_ENV}}
        {{.FILE_ENV}}.*

        # Testing
        {{.DIR_PLAYWRIGHT}}/

        # Via framework
        {{.DIR_VIA}}/

        # IDE & OS
        .vscode/
        .DS_Store
        EOF

  git:commit:
    desc: Generate gitignore, commit and push changes
    cmds:
      - task: generate:gitignore
      - git add -A
      - git commit -m "{{.MESSAGE}}" || true
      - git push
      - |
        REPO=$(gh repo view --json owner,name --jq '"\(.owner.login)/\(.name)"' 2>/dev/null || echo "")
        if [ -n "$REPO" ]; then
          echo ""
          echo "✓ Pushed to: https://github.com/$REPO"
          echo ""
        fi

  # ============================================================================
  # Help
  # ============================================================================

  help:
    desc: Show help
    cmds:
      - task --list
