version: '3'

dotenv: ['.env']

vars:
  # Project
  PROJECT_NAME: ubuntu-website
  DOMAIN: www.ubuntusoftware.net

  # Cloudflare Account
  CF_ACCOUNT_ID: 7384af54e33b8a54ff240371ea368440

  # Deployment URLs
  URL_PRODUCTION: https://www.ubuntusoftware.net
  URL_PREVIEW: https://ubuntu-website.pages.dev
  URL_DEV: http://localhost:1313

  # Cloudflare Dashboard URLs
  CF_DASH_BASE: https://dash.cloudflare.com/{{.CF_ACCOUNT_ID}}
  CF_DASH_DOMAIN: '{{.CF_DASH_BASE}}/ubuntusoftware.net'
  CF_DASH_PAGES: '{{.CF_DASH_BASE}}/pages/view/{{.PROJECT_NAME}}'
  CF_DASH_PAGES_SETTINGS: '{{.CF_DASH_PAGES}}/settings/production'

  # Commands
  ENV_CMD: cmd/env/main.go
  TRANSLATE_CMD: cmd/translate/main.go

  # Directories
  DIR_PUBLIC: public
  DIR_RESOURCES: resources
  DIR_NODE_MODULES: node_modules
  DIR_BIN: bin
  DIR_PLAYWRIGHT: .playwright-mcp
  DIR_VIA: .via

  # Files
  FILE_HUGO_LOCK: .hugo_build.lock
  FILE_HUGO_STATS: hugo_stats.json
  FILE_BUN_LOCK: bun.lockb
  FILE_NPM_LOCK: package-lock.json
  FILE_ENV: .env

  # Hugo
  HUGO_BUILD_FLAGS: --gc --minify
  HUGO_DEV_FLAGS: --buildDrafts --buildFuture
  HUGO_PREVIEW_FLAGS: -e production --minify

  # Go
  GO_VERSION: "1.24"
  CGO_ENABLED: "1"

  # Wrangler
  WRANGLER_CMD: bunx wrangler

tasks:
  # ============================================================================
  # Default & Info
  # ============================================================================

  default:
    desc: Show project information (runs when you type 'task')
    cmds:
      - task: info

  info:
    desc: Show all URLs and project information
    cmds:
      - |
        # Get branch info
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

        echo "========================================"
        echo "Ubuntu Website - Project Info"
        echo "========================================"
        echo ""

        # Branch Status - PROMINENT DISPLAY
        echo "========== GIT BRANCH =========="
        if [ "$CURRENT_BRANCH" = "main" ]; then
          echo "WARNING: You are on MAIN branch"
          echo "Commits will deploy to PRODUCTION!"
        else
          echo "Current branch: $CURRENT_BRANCH"
          echo "(Safe to commit - preview deployment)"
        fi
        echo "================================"
        echo ""

        echo "Project: {{.PROJECT_NAME}}"
        echo "Domain: {{.DOMAIN}}"
        echo ""
        echo "Development URL:"
        echo "  Local: {{.URL_DEV}}"
        echo ""
        echo "Production URLs:"
        echo "  Main: {{.URL_PRODUCTION}}"
        echo "  Preview: {{.URL_PREVIEW}}"
        echo ""
        COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
        if [ "$COMMIT" != "unknown" ]; then
          echo "Current Commit Preview:"
          echo "  https://$COMMIT.ubuntu-website.pages.dev"
          echo ""
        fi
        echo "Cloudflare Dashboards:"
        echo "  Domain: {{.CF_DASH_DOMAIN}}"
        echo "  Pages: {{.CF_DASH_PAGES}}"
        echo "  Settings: {{.CF_DASH_PAGES_SETTINGS}}"
        echo ""
        echo "Quick Commands:"
        echo "  task setup             - Install Hugo, Bun, dependencies"
        echo "  task dev               - Start development server"
        echo "  task url:dev           - Open local dev in browser"
        echo "  task build             - Build production site"
        echo "  task git:deploy        - Commit and deploy to production"
        echo "  task cf:status         - Check deployment status"
        echo "  task url:prod          - Open production site"
        echo "  task help              - Show all available tasks"
        echo "========================================"

  # ============================================================================
  # Setup & Installation
  # ============================================================================

  setup:
    desc: Complete setup - install Hugo, Bun, and dependencies
    cmds:
      - task: install:hugo
      - task: install:bun
      - task: install:deps

  install:hugo:
    desc: Install Hugo Extended via Go
    cmds:
      - echo "Installing Hugo Extended..."
      - go install -tags extended github.com/gohugoio/hugo@latest
      - hugo version
    env:
      CGO_ENABLED: '{{.CGO_ENABLED}}'

  install:bun:
    desc: Install Bun
    cmds:
      - |
        if command -v bun &> /dev/null; then
          echo "Bun already installed"
        else
          curl -fsSL https://bun.sh/install | bash
        fi
      - bun --version

  install:deps:
    desc: Install dependencies
    cmds:
      - bun install
      - go mod download

  # ============================================================================
  # Environment Management
  # ============================================================================

  env:web:gui:
    desc: "Open web GUI for environment setup"
    cmds:
      - go run {{.ENV_CMD}} web-gui

  env:web:gui-mock:
    desc: "Open web GUI with mock validation (for testing)"
    cmds:
      - go run {{.ENV_CMD}} web-gui-mock

  # ============================================================================
  # Development
  # ============================================================================

  dev:
    desc: Start Hugo development server
    cmds:
      - |
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

        echo "========================================"
        echo "Hugo Development Server"
        echo "========================================"
        echo ""
        if [ "$CURRENT_BRANCH" = "main" ]; then
          echo "Branch: MAIN (production)"
        else
          echo "Branch: $CURRENT_BRANCH (preview)"
        fi
        echo ""
        echo "Local URL: {{.URL_DEV}}"
        echo ""
        echo "Quick Commands:"
        echo "  task url:dev   - Open in browser"
        echo "  Ctrl+C         - Stop server"
        echo "========================================"
        echo ""
      - hugo server {{.HUGO_DEV_FLAGS}}

  build:
    desc: Build production site
    cmds:
      - hugo {{.HUGO_BUILD_FLAGS}}

  preview:
    desc: Preview production build
    cmds:
      - hugo server {{.HUGO_PREVIEW_FLAGS}}

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.DIR_PUBLIC}} {{.DIR_RESOURCES}} {{.FILE_HUGO_LOCK}}

  # ============================================================================
  # Translation
  # ============================================================================

  translate:check:
    desc: Check which files need translation
    cmds:
      - go run {{.TRANSLATE_CMD}} --check

  translate:all:
    desc: Translate all changed content
    cmds:
      - go run {{.TRANSLATE_CMD}} --all

  translate:lang:
    desc: Translate to specific language
    cmds:
      - go run {{.TRANSLATE_CMD}} --lang={{.LANG}}
    requires:
      vars: [LANG]

  translate:i18n:
    desc: Translate i18n files
    cmds:
      - go run {{.TRANSLATE_CMD}} --i18n

  # ============================================================================
  # Cloudflare Pages (DEPRECATED - using Git integration)
  # ============================================================================
  # NOTE: Deployments now happen automatically via Cloudflare Pages Git integration
  # These tasks are kept for reference but should not be used for regular deployments

  cf:login:
    desc: "[DEPRECATED] Login to Cloudflare"
    cmds:
      - 'echo "DEPRECATED: This task is no longer needed with Git integration"'
      - '{{.WRANGLER_CMD}} login'

  cf:init:
    desc: "[DEPRECATED] Initialize Cloudflare Pages project"
    cmds:
      - 'echo "DEPRECATED: Project is configured via Cloudflare dashboard"'
      - '{{.WRANGLER_CMD}} pages project create {{.PROJECT_NAME}} --production-branch=main'

  cf:deploy:
    desc: "[DEPRECATED] Deploy to Cloudflare Pages - Use git push instead"
    deps: [build]
    cmds:
      - 'echo "DEPRECATED: Deployments happen automatically on git push"'
      - 'echo "Just run: git push"'
      - exit 1

  cf:status:
    desc: Check deployment status
    cmds:
      - |
        echo "========================================"
        echo "Cloudflare Pages Status"
        echo "========================================"
        echo "Project: {{.PROJECT_NAME}}"
        echo ""
        echo "URLs:"
        echo "  Production: {{.URL_PRODUCTION}}"
        echo "  Preview: {{.URL_PREVIEW}}"
        echo ""
        echo "Dashboards:"
        echo "  Pages: {{.CF_DASH_PAGES}}"
        echo "  Settings: {{.CF_DASH_PAGES_SETTINGS}}"
        echo ""
        echo "Recent Deployments:"
        echo "========================================"
      - '{{.WRANGLER_CMD}} pages deployment list --project-name={{.PROJECT_NAME}}'

  cf:logs:
    desc: View deployment logs
    cmds:
      - |
        echo "========================================"
        echo "Recent Deployments"
        echo "========================================"
        echo "Dashboard: {{.CF_DASH_PAGES}}"
        echo ""
      - '{{.WRANGLER_CMD}} pages deployment list --project-name={{.PROJECT_NAME}} | head -10'

  cf:tail:
    desc: Tail latest deployment logs
    cmds:
      - |
        echo "========================================"
        echo "Tailing Deployment Logs"
        echo "========================================"
        echo "Dashboard: {{.CF_DASH_PAGES}}"
        echo ""
      - '{{.WRANGLER_CMD}} pages deployment tail --project-name={{.PROJECT_NAME}}'

  cf:secret:set:
    desc: Set a secret for Cloudflare Pages (e.g., HUGO_VERSION)
    cmds:
      - 'echo "Setting secret for Pages project..."'
      - '{{.WRANGLER_CMD}} pages secret put {{.CLI_ARGS}} --project-name={{.PROJECT_NAME}}'

  cf:secret:list:
    desc: List secrets for Cloudflare Pages
    cmds:
      - '{{.WRANGLER_CMD}} pages secret list --project-name={{.PROJECT_NAME}}'

  cf:delete:
    desc: "[DANGEROUS] Delete Cloudflare Pages project"
    cmds:
      - 'echo "WARNING: This will delete your Pages project!"'
      - '{{.WRANGLER_CMD}} pages project delete {{.PROJECT_NAME}}'

  # ============================================================================
  # CI/CD (DEPRECATED - using Cloudflare Pages Git integration)
  # ============================================================================
  # NOTE: These tasks were used by GitHub Actions, which is now disabled

  ci:setup:
    desc: "[DEPRECATED] Setup CI environment"
    cmds:
      - 'echo "DEPRECATED: CI/CD now handled by Cloudflare Pages"'
      - go install -tags extended github.com/gohugoio/hugo@latest
      - bun install
      - go mod download
    env:
      CGO_ENABLED: '{{.CGO_ENABLED}}'

  ci:build:
    desc: "[DEPRECATED] Build in CI"
    deps: [build]

  ci:deploy:
    desc: "[DEPRECATED] Deploy from CI"
    cmds:
      - 'echo "DEPRECATED: Deployments now handled by Cloudflare Pages Git integration"'
      - exit 1

  # ============================================================================
  # Code Quality
  # ============================================================================

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  lint:
    desc: Lint code
    cmds:
      - go vet ./...

  test:
    desc: Run tests
    cmds:
      - go test ./... -v

  # ============================================================================
  # Git Utilities
  # ============================================================================

  generate:gitignore:
    desc: Generate .gitignore from vars
    cmds:
      - |
        cat > .gitignore << 'EOF'
        # Hugo
        {{.DIR_PUBLIC}}/
        {{.DIR_RESOURCES}}/
        {{.FILE_HUGO_LOCK}}
        {{.FILE_HUGO_STATS}}

        # Node/Bun
        {{.DIR_NODE_MODULES}}/
        {{.FILE_BUN_LOCK}}
        {{.FILE_NPM_LOCK}}

        # Go
        {{.DIR_BIN}}/
        go.sum
        *.test
        *.out

        # Environment
        {{.FILE_ENV}}
        {{.FILE_ENV}}.*

        # Testing
        {{.DIR_PLAYWRIGHT}}/

        # Via framework
        {{.DIR_VIA}}/

        # IDE & OS
        .vscode/
        .DS_Store
        EOF

  git:status:
    desc: Show git status and recent commits
    cmds:
      - |
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

        echo "========================================"
        echo "GIT STATUS"
        echo "========================================"
        echo ""
        echo "========== CURRENT BRANCH =========="
        if [ "$CURRENT_BRANCH" = "main" ]; then
          echo "WARNING: Branch: MAIN (production)"
        else
          echo "Branch: $CURRENT_BRANCH (preview)"
        fi
        echo "===================================="
        echo ""
      - git status
      - 'echo ""'
      - 'echo "Recent commits:"'
      - git log --oneline -5

  git:commit:
    desc: Generate gitignore, commit and push changes (triggers Cloudflare deployment)
    cmds:
      - |
        # Check current branch
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

        echo ""
        echo "========================================"
        echo "GIT COMMIT & PUSH"
        echo "========================================"
        echo "Branch: $CURRENT_BRANCH"
        echo ""

        if [ "$CURRENT_BRANCH" = "main" ]; then
          echo "WARNING WARNING WARNING WARNING WARNING"
          echo ""
          echo "You are committing to MAIN branch!"
          echo "This will trigger PRODUCTION deployment"
          echo "to: {{.URL_PRODUCTION}}"
          echo ""
          echo "WARNING WARNING WARNING WARNING WARNING"
          echo ""
          echo "Press Ctrl+C to cancel, or"
          read -p "Type 'DEPLOY' to continue: " CONFIRM
          if [ "$CONFIRM" != "DEPLOY" ]; then
            echo "Cancelled."
            exit 1
          fi
        else
          echo "Safe: Preview deployment only"
          echo ""
        fi

      - task: generate:gitignore
      - git add -A
      - git commit -m "{{.MESSAGE}}" || true
      - git push
      - |
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        REPO=$(gh repo view --json owner,name --jq '"\(.owner.login)/\(.name)"' 2>/dev/null || echo "")
        COMMIT=$(git rev-parse --short HEAD)

        echo ""
        echo "========================================"
        if [ "$CURRENT_BRANCH" = "main" ]; then
          echo "PRODUCTION Deployment Triggered"
        else
          echo "Preview Deployment Triggered"
        fi
        echo "========================================"
        echo "Branch: $CURRENT_BRANCH"

        if [ -n "$REPO" ]; then
          echo "GitHub: https://github.com/$REPO"
        fi

        echo ""
        if [ "$CURRENT_BRANCH" = "main" ]; then
          echo "Production URL:"
          echo "  {{.URL_PRODUCTION}}"
          echo ""
        fi
        echo "Preview URL:"
        echo "  {{.URL_PREVIEW}}"
        echo ""
        echo "Commit Preview (after deployment):"
        echo "  https://$COMMIT.ubuntu-website.pages.dev"
        echo ""
        echo "Cloudflare Dashboards:"
        echo "  Pages: {{.CF_DASH_PAGES}}"
        echo "  Settings: {{.CF_DASH_PAGES_SETTINGS}}"
        echo ""
        echo "Quick Commands:"
        echo "  task cf:status  - Check deployment status"
        echo "  task cf:logs    - View deployment logs"
        echo "  task url:prod   - Open production site"
        echo "========================================"

  git:deploy:
    desc: Quick commit and deploy to Cloudflare Pages
    cmds:
      - task: git:commit
        vars:
          MESSAGE: '{{.MESSAGE | default "Update site"}}'

  git:preview:
    desc: Create a preview branch for testing (triggers preview deployment)
    cmds:
      - git checkout -b preview/{{.BRANCH}}
      - git push -u origin preview/{{.BRANCH}}
      - |
        COMMIT=$(git rev-parse --short HEAD)

        echo ""
        echo "========================================"
        echo "Preview Branch Created"
        echo "========================================"
        echo "Branch: preview/{{.BRANCH}}"
        echo ""
        echo "Preview URLs (after deployment):"
        echo "  Main: {{.URL_PREVIEW}}"
        echo "  Commit: https://$COMMIT.ubuntu-website.pages.dev"
        echo ""
        echo "Dashboard: {{.CF_DASH_PAGES}}"
        echo ""
        echo "Quick Commands:"
        echo "  task cf:status  - Check deployment status"
        echo "  task cf:logs    - View deployment logs"
        echo "========================================"
    requires:
      vars: [BRANCH]

  git:cleanup-preview:
    desc: Delete a preview branch
    cmds:
      - git checkout main
      - git branch -D preview/{{.BRANCH}}
      - git push origin --delete preview/{{.BRANCH}}
      - 'echo "✓ Deleted preview branch: preview/{{.BRANCH}}"'
    requires:
      vars: [BRANCH]

  git:sync:
    desc: Sync with remote and show deployment status
    cmds:
      - git pull
      - 'echo ""'
      - 'echo "Latest deployments:"'
      - task: cf:logs

  # ============================================================================
  # URL Helpers
  # ============================================================================

  url:dev:
    desc: Open local development server in browser
    cmds:
      - open {{.URL_DEV}}

  url:prod:
    desc: Open production website in browser
    cmds:
      - open {{.URL_PRODUCTION}}

  url:preview:
    desc: Open preview website in browser
    cmds:
      - open {{.URL_PREVIEW}}

  url:commit:
    desc: Open commit preview URL in browser
    cmds:
      - |
        COMMIT=$(git rev-parse --short HEAD)
        open https://$COMMIT.ubuntu-website.pages.dev

  cf:open:
    desc: Open Cloudflare Pages dashboard in browser
    cmds:
      - open {{.CF_DASH_PAGES}}

  cf:open:settings:
    desc: Open Cloudflare Pages settings in browser
    cmds:
      - open {{.CF_DASH_PAGES_SETTINGS}}

  cf:open:domain:
    desc: Open domain dashboard in browser
    cmds:
      - open {{.CF_DASH_DOMAIN}}

  # ============================================================================
  # Help
  # ============================================================================

  help:
    desc: Show help
    cmds:
      - task --list
