package mailerlite

import "fmt"

// PrintUsage prints the CLI usage information.
func PrintUsage() {
	fmt.Println("mailerlite - CLI tool for MailerLite subscriber management")
	fmt.Println()
	fmt.Println("Usage:")
	fmt.Println("  mailerlite [flags] <command> [subcommand] [args]")
	fmt.Println()
	fmt.Println("Commands:")
	fmt.Println("  subscribers list              List all subscribers")
	fmt.Println("  subscribers count             Count total subscribers")
	fmt.Println("  subscribers get EMAIL         Get subscriber by email")
	fmt.Println("  subscribers add EMAIL [NAME]  Add or update subscriber")
	fmt.Println("  subscribers delete EMAIL      Delete subscriber")
	fmt.Println("  groups list                   List all groups")
	fmt.Println("  groups create NAME            Create a new group")
	fmt.Println("  groups subscribers ID         List subscribers in a group")
	fmt.Println("  groups assign ID EMAIL        Assign subscriber to group")
	fmt.Println("  groups unassign ID EMAIL      Remove subscriber from group")
	fmt.Println("  forms list                    List all forms")
	fmt.Println("  forms subscribers ID          List subscribers for a form")
	fmt.Println("  webhooks list                 List all webhooks")
	fmt.Println("  webhooks create URL [EVENTS]  Create a webhook (default: subscriber.created)")
	fmt.Println("  webhooks delete ID            Delete a webhook")
	fmt.Println("  automations list              List all automations")
	fmt.Println("  automations get ID            Get automation details")
	fmt.Println("  stats                         Show account statistics")
	fmt.Println("  open [TARGET]                 Open dashboard in browser")
	fmt.Println("  releases latest               Show latest GitHub release")
	fmt.Println("  releases list                 List all GitHub releases")
	fmt.Println("  releases urls                 Show release URLs for email templates")
	fmt.Println("  server [PORT=8086]            Start webhook server for Web3Forms")
	fmt.Println()
	fmt.Println("Open Targets:")
	fmt.Println("  dashboard (default), subscribers, groups, forms, automations")
	fmt.Println("  campaigns, webhooks, integrations, api")
	fmt.Println()
	fmt.Println("Webhook Events:")
	fmt.Printf("  %s, %s, %s\n", EventSubscriberCreated, EventSubscriberUpdated, EventSubscriberUnsubscribed)
	fmt.Printf("  %s, %s\n", EventSubscriberAddedToGroup, EventSubscriberRemovedFromGroup)
	fmt.Printf("  %s, %s, %s\n", EventSubscriberBounced, EventSubscriberAutomationTriggered, EventSubscriberAutomationComplete)
	fmt.Printf("  %s, %s, %s\n", EventCampaignSent, EventCampaignOpened, EventCampaignClicked)
	fmt.Println()
	fmt.Println("Flags:")
	fmt.Println("  -github-issue    Output markdown for GitHub issue")
	fmt.Println("  -v               Verbose output")
	fmt.Println("  -version         Show version")
	fmt.Println()
	fmt.Println("Environment:")
	fmt.Println("  MAILERLITE_API_KEY    API key (required)")
	fmt.Println()
	fmt.Printf("Get API key from: %s\n", APIKeyURL)
	fmt.Println()
	fmt.Println("Dashboard URLs:")
	fmt.Printf("  Dashboard:     %s\n", DashboardURL)
	fmt.Printf("  Subscribers:   %s\n", SubscribersURL)
	fmt.Printf("  Groups:        %s\n", GroupsURL)
	fmt.Printf("  Forms:         %s\n", FormsURL)
	fmt.Printf("  Automations:   %s\n", AutomationsURL)
	fmt.Printf("  Webhooks:      %s\n", WebhooksURL)
}
